example=ng serve example --port 4301 --host=0.0.0.0 --disable-host-check --public-host=example.com:4201
sample=ng serve sample --port 4302 --host=0.0.0.0 --disable-host-check --public-host=sample.com:4202
