name: slidewsl

services:

  # --------------------------------------------------------------------------------

  devcontainer:
    container_name: devcontainer
    build:
      context: devcontainer
      args:
        - USER=${SLIDEWSL_USERNAME}
        - UID=${SLIDEWSL_WSL_UID}
        - GID=${SLIDEWSL_WSL_GID}
    hostname: devcontainer
    network_mode: host
    restart: no
    env_file:
      - .env
      - path: .env.override
        required: false
    environment:
      DOCKER_HOST: ${SLIDEWSL_DOCKER_HOST_IN_CONTAINER}
      COMPOSE_FILE: ${SLIDEWSL_COMPOSE_FILE_PATH_IN_CONTAINER}/compose.yaml
    stdin_open: true
    tty: true
    volumes:
      - ${SLIDEWSL_SRC_MOUNT}:${SLIDEWSL_SRC_MOUNT_IN_CONTAINER}
      - ${SLIDEWSL_SCRIPT_PATH}:${SLIDEWSL_COMPOSE_FILE_PATH_IN_CONTAINER}:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    profiles:
      - devcontainer

  # --------------------------------------------------------------------------------

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8000:80"
    restart: unless-stopped
    profiles:
      - web

  # --------------------------------------------------------------------------------

  angular_node_modules:
    build:
      context: angular
      target: node_base
      additional_contexts:
        shared: _shared
    user: "${SLIDEWSL_WSL_UID}:${SLIDEWSL_WSL_GID}"
    environment:
      ANGULAR_ROOT: ${SLIDEWSL_ANGULAR_ROOT}
    volumes:
      # bind mount the top-level, so we don't automatically create the subfolder as root;
      # instead, we'll build it out as needed at runtime as part of the entrypoint
      - ${SLIDEWSL_SRC_MOUNT}:${SLIDEWSL_SRC_MOUNT_IN_CONTAINER}
    deploy:
      replicas: 0

  angular_app_build:
    extends:
      service: angular_node_modules
    build:
      target: app_build

  angular_devserver:
    container_name: angular_devserver
    extends:
      service: angular_node_modules
    build:
      target: dev_server
    environment:
      APPS: ${APPS:-unknown}
    ports:
      - 0.0.0.0:4200-4210:4200-4210
    deploy:
      replicas: 1
    profiles:
      - devserver

  # --------------------------------------------------------------------------------
