name: slidewsl

networks:
  php-fpm:
  keydb:
  mysql:
  angular_dev_server:

volumes:
  keydb:

services:

  # --------------------------------------------------------------------------------

  init:
    image: alpine:3.19.1
    depends_on:
      init0:
        condition: service_completed_successfully

  init0:
    image: alpine:3.19.1
    user: "${WSL_UID}:${WSL_GID}"
    command: "fix-folders.sh"
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
    volumes:
      - ./_shared:/usr/local/bin/
      - /:/host
      #- /mnt:/mnt
      #- /home:/home

  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------

  angular:
    build:
      context: angular
      additional_contexts:
        shared: _shared
      target: base
      args:
        - NODE_VERSION=$NODE_VERSION
        - NG_CLI_VERSION=$NG_CLI_VERSION
    user: "${WSL_UID}:${WSL_GID}"
    volumes:
      - ${SLIDEWSL_ANGULAR_ROOT_IN_WSL}:/angular
      - ./angular/scripts:/usr/local/bin/angular-scripts/
      - ./angular/conf:/usr/local/etc/angular/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-angular.env
        required: false
    depends_on:
      - init
    profiles:
      - angular

  angular_dev_server:
    container_name: angular_dev_server
    extends:
      service: angular
    build:
      target: dev_server
    environment:
      APPS: ${APPS:-app-not-specified}
    networks:
      - angular_dev_server
    depends_on:
      - init
      - nginx

  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------

  nginx:
    container_name: nginx
    build:
      context: nginx
      additional_contexts:
        shared: _shared
    user: "${WSL_UID}:${WSL_GID}"
    ports:
      - "0.0.0.0:4200-4210:4200-4210"
      - "0.0.0.0:443:4430"
    networks:
      - php-fpm
      - angular_dev_server
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ${SLIDEWSL_ANGULAR_ROOT_IN_WSL}:/angular
      - ${SLIDEWSL_LARAVEL_ROOT_IN_WSL}:/laravel
      - ${SLIDEWSL_WEB_ROOT_IN_WSL}:/webroot
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-nginx.env
        required: false
    depends_on:
      - init
      - php-fpm

  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------

  php:
    build:
      context: php
      additional_contexts:
        shared: _shared
      target: base
      args:
        - PHP_VERSION=$PHP_VERSION
        - PHP_REDIS_VERSION=$PHP_REDIS_VERSION
        - XDEBUG_VERSION=$XDEBUG_VERSION
        - COMPOSER_HASH=$COMPOSER_HASH
        - COMPOSER_VERSION=$COMPOSER_VERSION
        - PHP_CS_FIXER_VERSION=$PHP_CS_FIXER_VERSION
        - PHP_STAN_VERSION=$PHP_STAN_VERSION
        - PSALM_VERSION=$PSALM_VERSION
    user: "${WSL_UID}:${WSL_GID}"
    volumes:
      - ${SLIDEWSL_WEB_ROOT_IN_WSL}:/webroot
      - ${SLIDEWSL_LARAVEL_ROOT_IN_WSL}:/laravel
      - ./php/scripts:/usr/local/bin/php-scripts/
      - ./php/conf:/etc/php/conf.d/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-php.env
        required: false
    depends_on:
      - init
    profiles:
      - php

  php-fpm:
    container_name: php-fpm
    extends:
      service: php
    build:
      target: php-fpm
    networks:
      - php-fpm
      - keydb
      - mysql
    environment:
      WSL2_GATEWAY: ${WSL2_GATEWAY}
      PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d:/etc/php/conf.d
    depends_on:
      - init
      - keydb-node1
      - mysql
    profiles:
      - ""

  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------

  keydb-node1:
    container_name: keydb-node1
    hostname: keydb-node1
    build:
      context: keydb
      additional_contexts:
        shared: _shared
    user: "${WSL_UID}:${WSL_GID}"
    networks:
      - keydb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - keydb:/data
      - ./keydb/keydb-node1:/etc/keydb
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-keydb.env
        required: false

  keydb-node2:
    container_name: keydb-node2
    hostname: keydb-node2
    extends:
      service: keydb-node1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - keydb:/data
      - ./keydb/keydb-node2:/etc/keydb

  keydb-node3:
    container_name: keydb-node3
    hostname: keydb-node3
    extends:
      service: keydb-node1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - keydb:/data
      - ./keydb/keydb-node3:/etc/keydb

  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------
  # --------------------------------------------------------------------------------

  mysql:
    container_name: mysql
    build:
      context: mysql
      additional_contexts:
        shared: _shared
    user: "${WSL_UID}:${WSL_GID}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mysql/scripts:/usr/local/bin/mysql-scripts/
      - ./mysql/conf/docker.cnf:/etc/my.cnf
      - ${SLIDEWSL_DB_ROOT_IN_WSL}:/var/lib/mysql
    depends_on:
      - init
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-mysql.env
        required: false

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: phpmyadmin
      additional_contexts:
        shared: _shared
    user: "${WSL_UID}:${WSL_GID}"
    environment:
      - PMA_HOST=mysql
    networks:
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./phpmyadmin/conf.d:/etc/phpmyadmin/conf.d
    ports:
      - "0.0.0.0:8080:80"
    env_file:
      - docker-base.env
      - path: docker-custom.env
        required: false
      - path: docker-phpmyadmin.env
        required: false
    depends_on:
      - mysql

  # --------------------------------------------------------------------------------
